language: node_js
node_js:
- '10'
install:
- npm ci
cache:
  directories:
  - "$HOME/.npm"
script:
- npm run lint
- npm test
after_success:
- npm run coverage
git:
  depth: 1
notifications:
  email:
    on_success: never
    on_failure: always